version: '3.7'
services:
 postgresql:
  image: postgresql:12-alpine
  ports:
   - '5432:5432'
  volumes:
   - ./data:/var/lib/postgresql
  environment:
   - POSTGRES_DB=db
   - POSTGRES_USER=rasalam
   - POSTGRES_PASSWORD=mypassword
   - d