version: '3.7'
services:
 postgres:
  image: postgres:latest
  ports:
   - '5432:5432'
  volumes:
   - ./data:/var/lib/postgresql
  environment:
   - MYSQL_RANDOM_ROOT_PASSWORD=yes
   - MYSQL_DATABASE=app
   - MYSQL_USER=app
   - MYSQL_PASSWORD=mypassword
   - d
